#
###################################
# Site wide configuration
####################################
#
title: Shahriyar Nasir's Personal Blog
email: contact@snasir.ca
description: Shahriyar Nasir blogs about software, hardware, and technology
url: https://snasir.ca # the base hostname & protocol for your site
keywords: ["Software", "Engineering", "Programming", "Code", "Ruby", "Rails"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Toronto
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /posts/:year/:month/:day/:title/
plugins:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Shahriyar Nasir
  avatar:
  job: "Software Engineer"
  bio: "Full Stack Web Developer @Nulogy • Empath • Innovator • Collaborator"
  email: contact@snasir.ca
  disqus-shortname: snasirca
  twitter: ShahriyarNasir
  facebook:
  google:
    plus:
    analytics: UA-27733934-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: snasirca
  stackoverflow: 998598/snasirca
  linkedin: shahriyar
  xing:
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  youtube:
  soundcloud:
  weibo:
  flickr:
  codepen:
  telegram:
  angellist: snasirca
  meetup: 89337752
  medium: ShahriyarNasir
  goodreads: 62723093-shahriyar
